export enum OrderStatus {
  PENDING_PAYMENT = "PENDING_PAYMENT",
  PAID = "PAID",
  CONFIRMED = "CONFIRMED",
  PACKING = "PACKING",
  SHIPPING = "SHIPPING",
  DELIVERED = "DELIVERED",
  CANCELLED = "CANCELLED",
  RETURN_REQUESTED = "RETURN_REQUESTED",
  RETURNED = "RETURNED",
  REFUNDED = "REFUNDED",
}

export enum PaymentStatus {
  PENDING = "PENDING",
  SUCCESS = "SUCCESS",
  FAILED = "FAILED",
  REFUNDED = "REFUNDED",
  PAYMENT_SHORTFALL = "PAYMENT_SHORTFALL",
  PAYMENT_OVERAGE = "PAYMENT_OVERAGE",
  PARTIAL_REFUND = "PARTIAL_REFUND",
}

export const ShipFee = 20000;
